# Generated by Django 5.1.2 on 2025-08-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('month', models.CharField(blank=True, max_length=20)),
                ('link', models.URLField(blank=True, help_text='Optional: Add a section link like #event1')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt_text', models.CharField(max_length=150)),
                ('show_in_homepage', models.BooleanField(default=True)),
            ],
        ),
    ]
