# Generated by Django 5.2.5 on 2025-08-08 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iskconapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional: A short description of the album.",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional: A representative image for the album.",
                        null=True,
                        upload_to="album_covers/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="show_in_homepage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="album",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the album this image belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="iskconapp.album",
            ),
        ),
    ]
