# Generated by Django 5.2.5 on 2025-08-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iskconapp", "0002_album_alter_galleryimage_show_in_homepage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryimage",
            options={"ordering": ["-id"]},
        ),
    ]
